// Literal presentation copy only; never translates catalogue names, identifiers or stored records.
export const hindiCopy: Record<string, string> = {
  "Choose or create the supplier": "सप्लायर चुनें या नया जोड़ें",
  "Choose an active catalogue product": "कैटलॉग से सक्रिय सामान चुनें",
  "Confirm the received unit and price unit":
    "मिली मात्रा और कीमत की इकाइयों की पुष्टि करें",
  "Enter the physical batch code": "मिले हुए बैच का नंबर भरें",
  "Confirm a complete, valid expiry date":
    "पूरी और सही एक्सपायरी तारीख की पुष्टि करें",
  "Expired stock cannot be received as sellable stock":
    "एक्सपायर सामान बिक्री के स्टॉक में नहीं जोड़ा जा सकता",
  "Received quantity must be positive": "मिली मात्रा शून्य से अधिक होनी चाहिए",
  "Received stock must contain whole base units":
    "मिली मात्रा में मूल इकाइयाँ पूरी होनी चाहिए",
  "Price conversion has fractions of a paise; enter reviewed prices per base unit":
    "कीमत बदलने पर पैसे का अंश बन रहा है; जाँची कीमत प्रति मूल इकाई भरें",
  "Selling price exceeds MRP": "बिक्री कीमत एमआरपी से अधिक है",
  "Enter an amount with up to two decimals":
    "अधिकतम दो दशमलव अंकों वाली रकम भरें",
  "Enter a non-negative quantity with up to three decimals":
    "शून्य या उससे अधिक मात्रा भरें, अधिकतम तीन दशमलव अंकों के साथ",
  "Confirm a valid invoice date, not in the future":
    "बिल की सही तारीख भरें, भविष्य की नहीं",
  "Enter the supplier invoice number": "सप्लायर का बिल नंबर भरें",
  "Add at least one received item": "कम से कम एक मिला सामान जोड़ें",
  "Review and confirm every item": "हर सामान की जाँच और पुष्टि करें",
  "Catalogue changed or item review is missing; confirm the items again":
    "कैटलॉग बदला है या जाँच बाकी है; सामान की दोबारा पुष्टि करें",
  "Enter a reason for the invoice adjustment": "बिल के समायोजन का कारण भरें",
  "Line totals must match the invoice total":
    "सामान और समायोजन का कुल बिल के कुल से मिलना चाहिए",
  "Synthetic example — no AI call was made.":
    "यह उदाहरण डेटा है — कोई AI कॉल नहीं की गई।",

  "Recording sale items… (up to 28 seconds)":
    "बिक्री की दवाएँ रिकॉर्ड हो रही हैं… (अधिकतम 28 सेकंड)",
  Formulation: "दवा का रूप",
  "Extra units (box=100, pack=20)": "अतिरिक्त इकाइयाँ (box=100, pack=20)",
  "Reorder level in base units": "मँगाने की सीमा (मूल इकाई)",
  "Owner price update": "मालिक द्वारा मूल्य बदलाव",
  "Update selling price": "बिक्री मूल्य बदलें",
  "quarantine disposal": "अलग रखे माल का निपटारा",
  "Recover from shop backups": "दुकान के बैकअप से बहाल करें",
  "Shop infrastructure": "दुकान की व्यवस्था",
  "Gateway reachable": "गेटवे उपलब्ध है",
  "Gateway unavailable or not paired": "गेटवे अनुपलब्ध है या जुड़ा नहीं है",
  "Request return": "वापसी का अनुरोध",
  "Returned base units": "वापस मिली मूल इकाइयाँ",
  "Originally supplied:": "पहले दी गई मात्रा:",
  "Enter only physically returned quantities in base units. Owner approval and refund execution are separate.":
    "वास्तव में वापस मिली मात्रा मूल इकाई में भरें। मालिक की अनुमति और रिफंड करना अलग चरण हैं।",
  "Counter assignment": "काउंटर का चयन",
  "Counter ID": "काउंटर आईडी",
  "Assign this counter": "यह काउंटर चुनें",
  "My cash collections": "मेरे द्वारा प्राप्त नकद",
  "s available": "उपलब्ध",
  "Preview device": "डेमो फ़ोन",
  "Cash collected": "प्राप्त नकद",
  "UPI collected": "प्राप्त UPI",
  "A clear view of sales, collections, and what needs attention.":
    "बिक्री, भुगतान और ध्यान देने योग्य जानकारी।",
  "Held orders, handoffs, and completed bills.":
    "रोके गए, सौंपे गए ऑर्डर और पूर्ण बिल।",
  "Credit belongs to a customer. Repayments are not new sales.":
    "उधार ग्राहक के खाते में रहता है। वसूली नई बिक्री नहीं है।",
  "Batch-level stock, expiry, and verified physical counts.":
    "बैच का स्टॉक, समाप्ति और जाँची गई भौतिक गिनती।",
  "One shared drawer. Every recorded movement has an actor.":
    "एक साझा दराज़। हर दर्ज लेन-देन के साथ कर्मचारी का नाम।",
  "Approvals and evidence that need a human decision.":
    "अनुमति और प्रमाण जिन पर इंसान का निर्णय चाहिए।",
  "Shop configuration, employee access, and registered devices.":
    "दुकान की सेटिंग, कर्मचारी की अनुमति और फ़ोन।",
  "Shop name": "दुकान का नाम",
  "Shop address": "दुकान का पता",
  "Drug licence number": "दवा लाइसेंस नंबर",
  "State code": "राज्य कोड",
  "Contact phone": "संपर्क फ़ोन",
  "Merchant UPI ID": "व्यापारी की UPI आईडी",
  "Local gateway URL": "स्थानीय गेटवे URL",
  "Upload invoice photo or PDF": "बिल की फ़ोटो या PDF अपलोड करें",
  "Extracting invoice…": "बिल पढ़ा जा रहा है…",
  "Received base units": "प्राप्त मूल इकाइयाँ",
  "Bonus base units": "बोनस मूल इकाइयाँ",
  "Selling price / base unit (₹)": "बिक्री मूल्य / मूल इकाई (₹)",
  "MRP / base unit (₹)": "MRP / मूल इकाई (₹)",
  "Verified cost / base unit (₹)": "जाँचा गया लागत मूल्य / मूल इकाई (₹)",
  "Line total including tax (₹)": "दवा की कर सहित राशि (₹)",
  "Handoff pending": "सौंपना बाकी",
  Held: "रुका हुआ",
  "No phone recorded": "फ़ोन दर्ज नहीं है",
  "Edit medicine": "दवा बदलें",
  Provisional: "अस्थायी",
  "Synced at close": "बंद करते समय सिंक",
  "Saved on this phone": "इस फ़ोन पर सहेजा गया",
  "Backed up at shop": "दुकान में बैकअप है",
  "Owner recovery required": "मालिक की सहायता आवश्यक",
  Active: "सक्रिय",
  Disabled: "बंद",
  "Can collect": "भुगतान ले सकते हैं",
  "Cannot collect": "भुगतान नहीं ले सकते",
  Disable: "बंद करें",
  Enable: "सक्रिय करें",
  Owner: "मालिक",
  Employee: "कर्मचारी",
  "Set your password": "अपना पासवर्ड बनाएँ",
  "Total cash (₹)": "कुल नकदी (₹)",
  Reason: "कारण",
  "Note, if any": "कोई टिप्पणी हो तो",
  "Leave in the drawer for the next opening (₹)":
    "अगली बार खोलने के लिए दराज़ में छोड़ें (₹)",
  "Ask the owner to approve credit": "मालिक से उधार की मंज़ूरी माँगें",
  "Quantity returned": "लौटाई गई मात्रा",
  "Other reason": "दूसरा कारण",
  "UPI reference of the refund": "वापसी का UPI रेफ़रेंस",
  "Find customer by name or phone": "नाम या फ़ोन से ग्राहक खोजें",
  "Customer name": "ग्राहक का नाम",
  Phone: "फ़ोन",
  "Find bill by number, medicine or customer":
    "बिल नंबर, दवा या ग्राहक से खोजें",
  "Give refund": "पैसे लौटाएँ",
  "Refund to the customer": "ग्राहक को लौटाना है",
  "Owes nothing today": "आज कुछ बाकी नहीं",
  "Sign in again": "फिर से साइन इन करें",
  "This phone was signed out, for example after a password change on another phone. Sales not yet sent stay on this phone and are sent after you sign in.":
    "यह फ़ोन साइन आउट हो गया है, जैसे किसी दूसरे फ़ोन पर पासवर्ड बदलने के बाद। जो बिक्री अभी भेजी नहीं गई वह इसी फ़ोन पर सुरक्षित है और साइन इन करने के बाद भेज दी जाएगी।",
  "Replace the temporary password your owner gave you.":
    "मालिक से मिले अस्थायी पासवर्ड को बदलें।",
  "Sign in to your shop to start billing and keep the day’s work in order.":
    "बिलिंग और दिन का हिसाब रखने के लिए लॉग इन करें।",
  "Temporary password": "अस्थायी पासवर्ड",
  "Signing in…": "लॉग इन हो रहा है…",
  "Update password": "पासवर्ड बदलें",
  "Open local review clip": "स्थानीय समीक्षा वीडियो खोलें",
  "Preserve clip with this case": "इस मामले का वीडियो सुरक्षित रखें",

  "Accept handoff": "ऑर्डर स्वीकार करें",
  "Account history": "खाते का इतिहास",
  "Add customer": "ग्राहक जोड़ें",
  "Add invoice line": "बिल में दवा जोड़ें",
  "Add medicine": "दवा जोड़ें",
  "Add supplier": "सप्लायर जोड़ें",
  "All time": "अब तक",
  "Amount (₹)": "राशि (₹)",
  "Approval requests": "अनुमति के अनुरोध",
  "Ask owner to approve discount": "छूट के लिए मालिक से अनुमति माँगें",
  "Awaiting the assigned collector.": "तय किए गए कर्मचारी की प्रतीक्षा है।",
  Barcode: "बारकोड",
  "Base unit": "मूल इकाई",
  "Batch code": "बैच कोड",
  "Bill saved": "बिल सहेज लिया गया",
  "Brand / product name": "ब्रांड / उत्पाद का नाम",
  COUNTER: "काउंटर",
  "Cash collected (₹)": "प्राप्त नकद (₹)",
  "Cash refunded (₹)": "वापस किया नकद (₹)",
  "Change in base units (negative to remove)":
    "मूल इकाई में बदलाव (घटाने के लिए ऋणात्मक)",
  "Choose a cashier": "कैशियर चुनें",
  "Close and reconcile drawer": "दराज़ बंद करके हिसाब मिलाएँ",
  "Close drawer": "दराज़ बंद करें",
  "Collect payment": "भुगतान लें",
  Completed: "पूर्ण",
  "Count actual": "वास्तविक नकद गिनें",
  Counted: "गिना गया",
  "Create employee account": "कर्मचारी का खाता बनाएँ",
  "Create report": "रिपोर्ट बनाएँ",
  "Device and synchronisation": "फ़ोन और सिंक",
  "Difference at close": "बंद करते समय अंतर",
  "Drawer history": "दराज़ का इतिहास",
  "Employee name": "कर्मचारी का नाम",
  Employees: "कर्मचारी",
  "End-of-day reports": "दिन के अंत की रिपोर्ट",
  "Estimated gross margin:": "अनुमानित सकल मार्जिन:",
  "Exceptions and camera pilot": "विसंगतियाँ और कैमरा परीक्षण",
  "Execute approved adjustment": "स्वीकृत सुधार लागू करें",
  "Expiry (YYYY-MM-DD)": "समाप्ति (वर्ष-महीना-दिन)",
  "Explore employee workspace": "कर्मचारी का डेमो देखें",
  "Find and confirm product": "उत्पाद खोजकर पुष्टि करें",
  "GST included · Confirm before collecting":
    "GST शामिल है · भुगतान लेने से पहले जाँचें",
  "GST rate (%) · verify from invoice": "GST दर (%) · बिल से जाँचें",
  "Generic / salt": "जेनेरिक / साल्ट",
  "Hand to cashier": "कैशियर को सौंपें",
  "Invite employee": "कर्मचारी जोड़ें",
  "Invoice date (YYYY-MM-DD)": "बिल की तारीख (वर्ष-महीना-दिन)",
  "Invoice total (₹)": "बिल का कुल (₹)",
  Item: "दवा",
  "Last seen": "आखिरी संपर्क",
  MANAGEMENT: "प्रबंधन",
  "MRP per base unit (₹)": "मूल इकाई का MRP (₹)",
  "May collect payments": "भुगतान लेने की अनुमति",
  "Merchant transaction reference": "व्यापारी भुगतान का संदर्भ",
  "Needs attention": "ध्यान दें",
  "New customer credit (₹)": "नया ग्राहक उधार (₹)",
  "New password · at least 12 characters": "नया पासवर्ड · कम से कम 12 अक्षर",
  "New supplier name (optional)": "नए सप्लायर का नाम (वैकल्पिक)",
  "No approvals waiting": "कोई अनुमति बाकी नहीं",
  "No open orders": "कोई खुला ऑर्डर नहीं",
  "Offline authorisation expires": "ऑफलाइन अनुमति समाप्त होगी",
  "Open drawer": "दराज़ खोलें",
  "Open today's drawer": "आज की दराज़ खोलें",
  "Opening cash (₹)": "शुरुआती नकद (₹)",
  "Opening float": "शुरुआती नकद",
  Order: "ऑर्डर",
  "Patient address": "मरीज़ का पता",
  "Patient name": "मरीज़ का नाम",
  "Physical opening count": "शुरुआती भौतिक गिनती",
  "Physically counted cash (₹)": "गिना गया नकद (₹)",
  "Post opening count": "शुरुआती गिनती दर्ज करें",
  "Post reviewed stock receipt": "जाँचा गया माल दर्ज करें",
  "Preparing a reviewable draft…": "जाँचने के लिए ड्राफ्ट तैयार हो रहा है…",
  "Prescriber address": "डॉक्टर का पता",
  "Prescriber name": "डॉक्टर का नाम",
  "Prescription reference": "पर्चे का संदर्भ",
  "Prescription register": "पर्चा रजिस्टर",
  "Purchase cost per base unit (₹), if known":
    "मूल इकाई का खरीद मूल्य (₹), यदि ज्ञात हो",
  "Receive stock": "माल प्राप्त करें",
  "Receive supplier invoice": "सप्लायर का बिल दर्ज करें",
  "Recent sales": "हाल की बिक्री",
  "Record cash movement": "नकद लेन-देन दर्ज करें",
  "Record executed refund": "किया गया रिफंड दर्ज करें",
  "Record movement": "लेन-देन दर्ज करें",
  "Record repayment": "उधार की वसूली दर्ज करें",
  "Recording sale items…": "बिक्री की दवाएँ रिकॉर्ड हो रही हैं…",
  "Recover sale": "बिक्री बहाल करें",
  "Refund UPI reference, if used": "रिफंड का UPI संदर्भ, यदि लागू हो",
  "Registered devices": "पंजीकृत फ़ोन",
  "Reject with reason": "कारण सहित अस्वीकार करें",
  "Remove item": "दवा हटाएँ",
  "Repayment amount (₹)": "वसूली की राशि (₹)",
  "Request discount (₹)": "माँगी गई छूट (₹)",
  "Request full return": "पूरा माल वापस लेने का अनुरोध",
  "Request owner approval": "मालिक की अनुमति माँगें",
  "Request stock adjustment": "स्टॉक सुधार का अनुरोध",
  "Resolution / evidence checked": "निष्कर्ष / जाँचा गया प्रमाण",
  "Resolve exception": "विसंगति का निपटारा करें",
  Retry: "दोबारा प्रयास",
  "Return line": "वापसी की दवा",
  "Review approval": "अनुमति की समीक्षा",
  "Review spoken items": "बोली गई दवाएँ जाँचें",
  Revoke: "अनुमति हटाएँ",
  Revoked: "अनुमति हटाई गई",
  Sales: "बिक्री",
  "Save customer": "ग्राहक सहेजें",
  "Save medicine": "दवा सहेजें",
  "Save resolution": "निष्कर्ष सहेजें",
  "Save shop settings": "दुकान की सेटिंग सहेजें",
  "Scan barcode": "बारकोड स्कैन करें",
  "Scan product barcode": "उत्पाद का बारकोड स्कैन करें",
  "Search aliases (comma separated)": "खोज के अन्य नाम (अल्पविराम से अलग)",
  "Selling price per base unit (₹)": "मूल इकाई का बिक्री मूल्य (₹)",
  Series: "सीरीज़",
  "Shop settings": "दुकान की सेटिंग",
  "Sign out": "लॉग आउट",
  "Strength and formulation": "ताकत और रूप",
  Supplier: "सप्लायर",
  "Supplier invoice number": "सप्लायर बिल नंबर",
  Synchronise: "सिंक करें",
  "Tablets per strip": "एक पत्ते में गोलियाँ",
  "Temporary password · at least 12 characters":
    "अस्थायी पासवर्ड · कम से कम 12 अक्षर",
  "UPI refunded (₹)": "वापस किया UPI (₹)",
  "UPI transaction reference": "UPI भुगतान का संदर्भ",
  "Unique username": "अलग यूज़रनेम",
  "Verified in merchant app": "व्यापारी ऐप में जाँचा",
  "Your first bill will appear here": "आपका पहला बिल यहाँ दिखाई देगा",
  "Your shop username": "दुकान का यूज़रनेम",
  "base units": "मूल इकाइयाँ",
  "completed bills · after returns": "पूर्ण बिल · वापसी घटाने के बाद",
  "devices with pending sales": "फ़ोन जिनकी बिक्री सिंक होना बाकी है",
  items: "दवाएँ",
  "medicines at reorder level": "दवाएँ जिन्हें मँगाना है",
  outstanding: "बकाया",
  quarantined: "अलग रखा माल",
  request: "अनुरोध",
  results: "परिणाम",
  "· Cash": "· नकद",
  "· Counter 01": "· काउंटर 01",
  "· Current ledger": "· वर्तमान खाता",
  "· Expected at close": "· बंद करते समय अपेक्षित",
  "· Owner": "· मालिक",
  "· Recorded stock": "· दर्ज स्टॉक",
  "· Revision": "· संशोधन",
  "· UPI": "· यूपीआई",
  "+ Record opening batch count": "+ शुरुआती बैच गिनती दर्ज करें",
  "A difference belongs to the shared drawer, not automatically to a specific employee.":
    "अंतर साझा दराज़ का है। इसे अपने-आप किसी कर्मचारी की कमी नहीं माना जाता।",
  "Camera observations are review candidates. Employee alerts and automatic theft conclusions are disabled.":
    "कैमरे की जानकारी समीक्षा के लिए है। कर्मचारी अलर्ट और चोरी का स्वचालित निष्कर्ष बंद हैं।",
  "Check the medicines and payment before confirming. Finalised bills are corrected through a recorded return.":
    "पुष्टि से पहले दवाएँ और भुगतान जाँचें। अंतिम बिल में सुधार दर्ज वापसी के माध्यम से होता है।",
  "Completed sales update this view. Customer repayments are counted as collections, not new sales.":
    "पूर्ण बिक्री यहाँ जुड़ती है। उधार की वसूली प्राप्त भुगतान में जुड़ती है, नई बिक्री में नहीं।",
  "Demo data stays separate from your real shop. Native development builds support encrypted offline billing.":
    "डेमो आपकी दुकान से अलग है। Android और iOS ऐप में सुरक्षित ऑफलाइन बिलिंग उपलब्ध है।",
  "EOD remains provisional until every device has synced.":
    "हर फ़ोन के सिंक होने तक दिन की रिपोर्ट अस्थायी रहती है।",
  "Hold a basket or hand an order to a cashier to continue it here.":
    "यहाँ से जारी रखने के लिए ऑर्डर रोकें या कैशियर को सौंपें।",
  "I checked mappings, packs, prices and received quantities against the invoice.":
    "मैंने बिल से दवाएँ, पैक, मूल्य और प्राप्त मात्रा जाँच ली है।",
  "I checked receipt in the merchant payment app":
    "मैंने व्यापारी भुगतान ऐप में राशि प्राप्त होना जाँच लिया है",
  "I physically counted this stock": "मैंने यह माल वास्तव में गिना है",
  "Opening counts, tax configuration and pharmacy record requirements have been verified for this shop.":
    "इस दुकान की शुरुआती गिनती, कर सेटिंग और फ़ार्मेसी रजिस्टर की आवश्यकताएँ जाँच ली गई हैं।",
  "Recorded as manually verified, not bank-confirmed.":
    "कर्मचारी द्वारा जाँचा गया दर्ज होगा। यह बैंक की पुष्टि नहीं है।",
  "Reduce unpaid invoice credit first. Enter only the money actually returned to the customer.":
    "पहले बिल का बकाया घटाएँ। केवल ग्राहक को वास्तव में लौटाई राशि भरें।",
  "Return to the held order to use this approval. It is valid only for the approved order version and amount.":
    "इस अनुमति का उपयोग रोके गए ऑर्डर में करें। यह केवल स्वीकृत ऑर्डर और राशि के लिए मान्य है।",
  "Review quantities before your next supplier order.":
    "अगला माल मँगाने से पहले मात्रा जाँचें।",
  "Review the source invoice. Convert supplier pack quantities and prices to base units before posting.":
    "मूल बिल जाँचें। दर्ज करने से पहले पैक की मात्रा और मूल्य को मूल इकाई में बदलें।",
  "Select the batch printed on the medicine you are supplying.":
    "दी जा रही दवा पर छपा बैच चुनें।",
  "Try a brand name, salt or barcode.": "ब्रांड, साल्ट या बारकोड से खोजें।",
  ". This is not net profit.": "। यह शुद्ध लाभ नहीं है।",
  "Saving…": "सहेजा जा रहा है…",
  "Collect with credit approval": "उधार की अनुमति से भुगतान लें",
  "Confirm payment & create bill": "भुगतान की पुष्टि करके बिल बनाएँ",
  "Cash + UPI": "नकद + UPI",
  "Open printable receipt": "प्रिंट करने योग्य बिल खोलें",
  "Print status": "प्रिंट की स्थिति",
  "Check print status": "प्रिंट की स्थिति जाँचें",
  "I checked the printer and paper": "मैंने प्रिंटर और कागज़ जाँच लिया है",
  "Reprint reason": "दोबारा प्रिंट करने का कारण",
  "Request audited reprint": "दर्ज कारण के साथ दोबारा प्रिंट करें",
  "Choose exact product": "सही उत्पाद चुनें",
  "No catalogue match. Use manual search.":
    "सूची में मिलान नहीं मिला। स्वयं खोजें।",
  "Choose another item": "दूसरी दवा चुनें",
  held: "रुका हुआ",
  handoff: "सौंपा गया",
  completed: "पूर्ण",
  pending: "बाकी",
  approved: "स्वीकृत",
  rejected: "अस्वीकृत",
  used: "उपयोग किया गया",
  open: "खुला",
  resolved: "निपटाया गया",
  local: "केवल फ़ोन पर",
  gateway: "गेटवे पर सुरक्षित",
  review: "समीक्षा",
  tablet: "गोली",
  strip: "पत्ता",
  box: "डिब्बा",
  bottle: "बोतल",
  sachet: "पाउच",
  piece: "नग",
  capsule: "कैप्सूल",
  vial: "शीशी",
  tube: "ट्यूब",
  respule: "रेस्प्यूल",
  syrup: "सिरप",
  cream: "क्रीम",
  drops: "ड्रॉप्स",
  injection: "इंजेक्शन",
  lotion: "लोशन",
  item: "सामान",
  stock: "स्टॉक",
  refund: "रिफंड",
  discount: "छूट",
  credit: "उधार",
  release: "अलग माल जारी करें",
  correction: "सुधार",
  damage: "खराब माल",
  expiry: "समाप्त माल",
  supplier_return: "सप्लायर को वापसी",
  introduced: "नकद जमा",
  withdrawal: "नकद निकासी",
  safe_transfer: "तिजोरी में स्थानांतरण",
  "No response from the server. This may already be saved, so do not collect payment again. It will be checked when the connection returns.":
    "सर्वर से जवाब नहीं आया। यह पहले ही दर्ज हो चुका हो सकता है, इसलिए दोबारा भुगतान न लें। कनेक्शन लौटने पर इसकी जाँच अपने-आप होगी।",
  "Username or password is wrong.": "यूज़रनेम या पासवर्ड गलत है।",
  "Too many tries. Wait 10 seconds and try again.":
    "बहुत बार कोशिश हुई। 10 सेकंड रुककर फिर कोशिश करें।",
  "Cannot reach the shop server. Check the internet and try again.":
    "दुकान के सर्वर से संपर्क नहीं हो रहा। इंटरनेट जाँचकर फिर कोशिश करें।",
  "Connection unavailable. Cash billing can continue in the mobile app while your authorisation is valid.":
    "कनेक्शन नहीं है। अनुमति वैध रहने तक ऐप में नकद बिल बनते रहेंगे।",
  "No connection, so this was not saved. Cash bills still work offline; try this again when the connection returns.":
    "कनेक्शन नहीं है, इसलिए यह दर्ज नहीं हुआ। नकद बिल बिना इंटरनेट के भी बनते हैं; कनेक्शन लौटने पर इसे फिर करें।",
  "An earlier action is still waiting for a server response. Try again after it is checked.":
    "पिछली कार्रवाई अभी सर्वर के जवाब का इंतज़ार कर रही है। उसकी जाँच होने के बाद फिर कोशिश करें।",
  "An action that had no response is now confirmed as saved. Check Orders before collecting again.":
    "जिस कार्रवाई का जवाब नहीं आया था, वह दर्ज होने की पुष्टि हो गई है। दोबारा भुगतान लेने से पहले ऑर्डर जाँचें।",
  "An action that had no response was not saved. Check Orders, then try again if needed.":
    "जिस कार्रवाई का जवाब नहीं आया था, वह दर्ज नहीं हुई। ऑर्डर जाँचें, फिर ज़रूरत हो तो दोबारा कोशिश करें।",
  "This cash sale is already saved on this phone and waiting to sync. Do not collect again.":
    "यह नकद बिक्री इस फ़ोन में पहले से दर्ज है और सिंक होने का इंतज़ार कर रही है। दोबारा भुगतान न लें।",
  "This sale was billed, handed over or cancelled elsewhere. Check Orders; do not collect it again here.":
    "इस बिक्री का बिल कहीं और बन गया, इसे सौंप दिया गया या रद्द कर दिया गया। ऑर्डर जाँचें; यहाँ दोबारा भुगतान न लें।",
  "Sale set aside. It will be confirmed automatically when the connection returns. Do not bill these items again; check Orders later.":
    "बिक्री अलग रखी गई। कनेक्शन लौटने पर इसकी पुष्टि अपने-आप होगी। इन सामानों का दोबारा बिल न बनाएँ; बाद में ऑर्डर जाँचें।",
  "No server response yet for this sale's payment. It may already be recorded, so do not collect again.":
    "इस बिक्री के भुगतान पर सर्वर का जवाब अभी नहीं आया। यह पहले ही दर्ज हो सकता है, इसलिए दोबारा भुगतान न लें।",
  "Check now": "अभी जाँचें",
  "Set aside and start a new sale": "अलग रखें और नई बिक्री शुरू करें",
  "Waiting for the server to confirm this sale. Do not collect payment again.":
    "सर्वर से इस बिक्री की पुष्टि का इंतज़ार है। दोबारा भुगतान न लें।",
  "Draft could not be saved. Retry before collecting payment.":
    "ड्राफ्ट सेव नहीं हो सका। भुगतान लेने से पहले फिर कोशिश करें।",
  "This sale is no longer open here. Check Orders before collecting.":
    "यह बिक्री अब यहाँ खुली नहीं है। भुगतान लेने से पहले ऑर्डर जाँचें।",
  Decline: "मना करें",
  "Take back": "वापस लें",
  "Take over": "अपने पास लें",
  "Cancel order": "ऑर्डर रद्द करें",
  "Reason for cancelling": "रद्द करने का कारण",
  "Only for an unbilled order the customer did not take. The cancellation and reason are recorded.":
    "सिर्फ़ उस बिना बिल वाले ऑर्डर के लिए जिसे ग्राहक ने नहीं लिया। रद्द करना और उसका कारण दर्ज होगा।",
  "Take back a handed-off order before cancelling it":
    "रद्द करने से पहले सौंपा गया ऑर्डर वापस लें",
  "Order was cancelled": "ऑर्डर रद्द हो चुका है",
  "Offered to": "सौंपा गया:",
  "Camera access is off. Allow it in Settings to scan, or search by name.":
    "कैमरे की अनुमति बंद है। स्कैन करने के लिए सेटिंग्स में अनुमति दें, या नाम से खोजें।",
  "No product has this barcode. Search by name, or ask the owner to add the barcode.":
    "इस बारकोड का कोई सामान नहीं मिला। नाम से खोजें, या मालिक से बारकोड जुड़वाएँ।",
  "Several products share this barcode. Choose the one you are supplying.":
    "यह बारकोड कई सामानों पर है। जो सामान दे रहे हैं, वही चुनें।",
  "No sellable stock is recorded for this product.":
    "इस सामान का बिक्री योग्य स्टॉक दर्ज नहीं है।",
  "The scanned pack's batch is expired. Do not supply it.":
    "स्कैन किए पैक का बैच एक्सपायर है। इसे न दें।",
  "The scanned pack's batch has no recorded stock. Check the pack and choose the batch you are supplying.":
    "स्कैन किए पैक के बैच का स्टॉक दर्ज नहीं है। पैक जाँचें और वही बैच चुनें जो दे रहे हैं।",
  "The scanned pack's batch is not in stock records. Check the pack and choose the batch you are supplying.":
    "स्कैन किए पैक का बैच स्टॉक रिकॉर्ड में नहीं है। पैक जाँचें और वही बैच चुनें जो दे रहे हैं।",
  "Open Settings": "सेटिंग्स खोलें",
  Dismiss: "बंद करें",
  "Barcodes (comma separated)": "बारकोड (कॉमा से अलग करें)",
  "Cash received (₹) · optional": "मिला नकद (₹) · वैकल्पिक",
  "Short by": "कम है",
  "Return to customer": "ग्राहक को लौटाएँ",
  "Cash received is less than the bill total": "मिला नकद बिल की रकम से कम है",
  "Load products from an Excel (.xlsx) or CSV export of your billing software or distributor, or paste rows copied from a spreadsheet. Nothing is saved until you review the rows and confirm.":
    "बिलिंग सॉफ़्टवेयर या डिस्ट्रीब्यूटर की Excel (.xlsx) या CSV फ़ाइल से सामान जोड़ें, या स्प्रेडशीट से कॉपी की गई पंक्तियाँ पेस्ट करें। पंक्तियाँ जाँचकर पुष्टि करने तक कुछ भी सेव नहीं होता।",
  "Columns it understands: item name, pack (10's, 1x15, 100ML), GST %, HSN, barcode, generic or salt, strength, form, schedule and company. Stock quantities are not imported here; record counted stock separately.":
    "समझे जाने वाले कॉलम: सामान का नाम, पैक (10's, 1x15, 100ML), GST %, HSN, बारकोड, जेनेरिक या साल्ट, ताकत, रूप, शेड्यूल और कंपनी। स्टॉक की मात्रा यहाँ नहीं जुड़ती; गिना हुआ स्टॉक अलग से दर्ज करें।",
  "Choose Excel or CSV file": "Excel या CSV फ़ाइल चुनें",
  "Or paste rows, including the header row":
    "या पंक्तियाँ पेस्ट करें, हेडर पंक्ति सहित",
  "Use pasted rows": "पेस्ट की गई पंक्तियाँ इस्तेमाल करें",
  "Choose another file": "दूसरी फ़ाइल चुनें",
  "Match columns": "कॉलम मिलाएँ",
  "Not in file": "फ़ाइल में नहीं",
  "GST % for rows without one (optional)":
    "जिन पंक्तियों में GST नहीं है उनके लिए GST % (वैकल्पिक)",
  "Choose the column with product names": "सामान के नाम वाला कॉलम चुनें",
  "No schedule column: every medicine will be marked OTC. Mark H and H1 medicines afterwards so the prescription register is required.":
    "शेड्यूल का कॉलम नहीं है: हर दवा OTC मानी जाएगी। बाद में H और H1 दवाएँ चिह्नित करें ताकि पर्चे का रजिस्टर ज़रूरी हो।",
  "No rows here.": "यहाँ कोई पंक्ति नहीं।",
  Done: "हो गया",
  "Rows with errors, repeated rows and products already in the catalogue are skipped. Existing products are never changed by an import.":
    "गलती वाली, दोहराई गई और कैटलॉग में पहले से मौजूद पंक्तियाँ छोड़ दी जाती हैं। इम्पोर्ट से मौजूदा सामान कभी नहीं बदलता।",
  "Import catalogue": "कैटलॉग इम्पोर्ट करें",
  "Split the file into parts of 20,000 rows or fewer":
    "फ़ाइल को 20,000 या कम पंक्तियों के हिस्सों में बाँटें",
  "No product rows found in the file":
    "फ़ाइल में सामान की कोई पंक्ति नहीं मिली",
  "Choose a file smaller than 15 MB": "15 MB से छोटी फ़ाइल चुनें",
  "Old .xls files cannot be read. Save it as .xlsx or CSV.":
    "पुरानी .xls फ़ाइल नहीं पढ़ी जा सकती। इसे .xlsx या CSV में सेव करें।",
  "The spreadsheet has no readable sheet":
    "स्प्रेडशीट में पढ़ने लायक शीट नहीं है",
  "Name is missing": "नाम नहीं है",
  "GST rate is not a valid number": "GST दर सही संख्या नहीं है",
  "GST rate is missing": "GST दर नहीं है",
  "GST from the default rate: check it": "GST डिफ़ॉल्ट दर से लिया गया: जाँचें",
  "Unusual GST rate: check it": "असामान्य GST दर: जाँचें",
  "No schedule given: marked OTC": "शेड्यूल नहीं दिया: OTC माना गया",
  "Schedule X: sales stay blocked": "शेड्यूल X: बिक्री बंद रहेगी",
  "Barcode was saved in Excel scientific notation and was ignored":
    "बारकोड Excel में वैज्ञानिक रूप (E+) में सेव था, इसलिए छोड़ा गया",
  "HSN code was not 4 to 8 digits and was left blank":
    "HSN कोड 4 से 8 अंकों का नहीं था, इसलिए खाली छोड़ा गया",
  "Row could not be read as a product":
    "यह पंक्ति सामान के रूप में नहीं पढ़ी जा सकी",
  "Unit could not be worked out: sold per piece":
    "इकाई तय नहीं हो सकी: प्रति नग बिकेगा",
  "Strip size unknown: add it before selling by strip":
    "पत्ते का साइज़ पता नहीं: पत्ते से बेचने से पहले जोड़ें",
  "Enter the product name": "सामान का नाम भरें",
  "Confirm the GST rate": "GST दर की पुष्टि करें",
  "Capsules per strip": "प्रति पत्ता कैप्सूल",
  "Count stock": "स्टॉक गिनें",
  "Scan the pack": "पैक स्कैन करें",
  "Batch number on the pack": "पैक पर छपा बैच नंबर",
  "Expiry as printed (for example 04/27)": "छपी हुई एक्सपायरी (जैसे 04/27)",
  "Counted quantity": "गिनी गई मात्रा",
  "MRP printed on the pack (₹)": "पैक पर छपा एमआरपी (₹)",
  "Selling price (₹), if below MRP": "बिक्री कीमत (₹), अगर एमआरपी से कम हो",
  "Purchase cost (₹), if known": "खरीद कीमत (₹), अगर पता हो",
  "Enter the batch number printed on the pack": "पैक पर छपा बैच नंबर भरें",
  "Batch number is too long": "बैच नंबर बहुत लंबा है",
  "This batch is already in stock. Use a stock adjustment to correct its count.":
    "यह बैच पहले से स्टॉक में है। गिनती सुधारने के लिए स्टॉक समायोजन करें।",
  "Enter the expiry as printed, for example 04/27":
    "छपी हुई एक्सपायरी भरें, जैसे 04/27",
  "This batch has expired. Keep it aside for return or disposal; it is not added as sellable stock.":
    "यह बैच एक्सपायर हो चुका है। इसे वापसी या नष्ट करने के लिए अलग रखें; यह बिक्री के स्टॉक में नहीं जुड़ता।",
  "Expires within 3 months": "3 महीने के अंदर एक्सपायर होगा",
  "Choose the counted unit and price unit": "गिनती और कीमत की इकाई चुनें",
  "Enter the counted quantity": "गिनी गई मात्रा भरें",
  "Counted quantity must be more than zero":
    "गिनी गई मात्रा शून्य से अधिक होनी चाहिए",
  "Counted quantity is too large": "गिनी गई मात्रा बहुत बड़ी है",
  "Counted quantity is too precise":
    "गिनी गई मात्रा में बहुत ज़्यादा दशमलव हैं",
  "Selling price cannot be more than MRP":
    "बिक्री कीमत एमआरपी से अधिक नहीं हो सकती",
  "Selling price must be more than zero":
    "बिक्री कीमत शून्य से अधिक होनी चाहिए",
  "Enter the MRP printed on the pack": "पैक पर छपा एमआरपी भरें",
  "Enter the MRP in rupees, up to two decimals":
    "एमआरपी रुपये में भरें, अधिकतम दो दशमलव",
  "Enter the selling price in rupees, up to two decimals":
    "बिक्री कीमत रुपये में भरें, अधिकतम दो दशमलव",
  "Enter the purchase cost in rupees, up to two decimals":
    "खरीद कीमत रुपये में भरें, अधिकतम दो दशमलव",
};
